### ISSUE TITLE
Any explicit support for encodings utf-8?

### ISSUE THREAD

**Issue by kevinhendricks** [blunderer/libroxml#63]
I looked and could not find any type of explicit encoding support.  No utf-8 iterator anyplace for parsing the source in proper unicode single character vs single-byte chunks, etc.  Any plans to add support for at least utf-8?

If at all interested you may want to  take a look at google's gumbo-parser for html code parsing (hosted here on github.com)  for an implementation of a nice utf-8 character iterator written in C for their parser and how it is used.

Thanks,
Kevin

**Comment by matkoniecz** [comment]
see https://github.com/sembruk/osm2xmap/issues/5 for case where the same file with utf-8 character is parsed in one environment and fails in the second,

**Comment by blunderer** [comment]
There is no support for UTF-8 in libroxml for now.

I might consider adding this as soon as I have some time. Thanks for the pointer, I'll definitely look there.
