### ISSUE TITLE
Unclear licensing between repo and webpage

### ISSUE THREAD

**Issue by kozross** [blunderer/libroxml#64]
Your webpage links to the GNU LGPLv3, while this code is actually under the LGPLv2, with some unusual linking provisions to boot. This is a bit unclear to me - which did you mean?

**Comment by matkoniecz** [comment]
> with some unusual linking provisions to boot

At least this exceptions seems to not limit LGPLv2 so at least it still LGPLv2 compatible.

**Comment by blunderer** [comment]
Hi, sorry for answering this late my github stopped sending notifications.

License of libroxml is LGPLv2.1 with static exception.
I will review the link on the homepage and fix it to reflect this
