### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by matkoniecz** [blunderer/libroxml#68]
32 bit Ubuntu 14.04.4 LTS (Lubuntu distribution).

 revision https://github.com/blunderer/libroxml/commit/1bc90ac506b50a06ee613b139405ff47ecc83c0a

```
./roxml.unitC 
ERROR	in file '/home/mateusz/Desktop/tmp/libroxml/unittest/roxml.test.c' function 'test_load_doc' at line 20  in thread id 0x0 in process 16571: 
	- root is NULL
FAILED:  file '/home/mateusz/Desktop/tmp/libroxml/unittest/roxml.test.c' function 'test_load_doc' in thread id 0x0 in process 16571: 1 error(s)
--------------------------------------------------------------------------------------
ERROR	in file '/home/mateusz/Desktop/tmp/libroxml/unittest/roxml.test.c' function 'test_load_fd' at line 36  in thread id 0x0 in process 16571: 
	- root is NULL
FAILED:  file '/home/mateusz/Desktop/tmp/libroxml/unittest/roxml.test.c' function 'test_load_fd' in thread id 0x0 in process 16571: 1 error(s)
--------------------------------------------------------------------------------------
ERROR	in file '/home/mateusz/Desktop/tmp/libroxml/unittest/roxml.test.c' function 'test_tree_on_doc' at line 53  in thread id 0x0 in process 16571: 
	- root is NULL
Segmentation fault (core dumped)
```

**Comment by blunderer** [comment]
There is no support for UTF-8 in libroxml for now.

I might consider adding this as soon as I have some time.

**Comment by matkoniecz** [comment]
I am bit surprised by closing known problem (test suite provided by program itself fails), typically bugs are open till issue is fixed.

**Comment by blunderer** [comment]
I apologize for this, I indeed went a bit fast and didn't mean to close this.
I see you reopened the issue, and I'll make sure to update it as soon as I make any progress on this feature.
I am not clear yet if/how the support for utf8 should be done. My concerns are regarding performances and compatibility.
I would probably make it a compile time option such as xpath support.

Anyhow, thanks for not letting me get sloppy, I truly appreciate it.
