### ISSUE TITLE
Libroxml does not transform XML escape characters

### ISSUE THREAD

**Issue by greendow** [blunderer/libroxml#71]
I wrote a XML file 'MyConfig.xml' as follows:
<configure>
<hardware_name>TestCircuitBoard&amp;1</hardware_name>
<hardware_count>10</hardware_count>
<configure>

My program is as follows:

#include <stdio.h>
#include <stdlib.h>
#include "roxml.h"

int main(void)
{
  node_t *root_node, *config_node, *hd_name_node, *text_node;
  char hd_name[128];

  memset(hd_name, 0, sizeof(hd_name));
  if ( !(root_node = roxml_load_doc("MyConfig.xml")) )
  {
    printf("Load config XML file failed at %s, line %d!\n", __FILE__, __LINE__);
	return (-1);
  }

  if ( !(config_node = roxml_get_chld(root_node, NULL, 0)) )
  {
	printf("Search node in config XML file failed at %s, line %d!\n", __FILE__, __LINE__);
	roxml_close(root_node);
	return (-1);
  }

  if ( !(hd_name_node = roxml_get_nodes(config_node, ROXML_ELM_NODE, "hardware_name", 0)) )
  {
	printf("Search node in config XML file failed at %s, line %d!\n", __FILE__, __LINE__);
	roxml_close(root_node);
	return (-1);
  }

  if ( !(text_node = roxml_get_txt(hd_name_node, 0)) )
  {
	printf("Search node in config XML file failed at %s, line %d!\n", __FILE__, __LINE__);
	roxml_close(root_node);
	return (-1);
  }

  if ( strlen(roxml_get_content(text_node, NULL, 0, NULL)) > sizeof(hd_name) )
  {
	printf("Hardware name byte length is beyond the upperbound in config XML file at %s, line %d!\n", __FILE__, __LINE__);
	roxml_close(root_node);
	return (-1); 
  }
  strcpy(hd_name, roxml_get_content(text_node, NULL, 0, NULL));
  printf("hardware name in XML file: %s\n", hd_name);

  roxml_close(root_node);
  #if defined(_WIN32) || defined(_WIN64)
  system("pause");
#endif
  return 0;
}

Libroxml version: 2.3.0
Expected output: hardware name in XML file: TestCircuitBoard&1

    Actual output: hardware name in XML file: TestCircuitBoard&amp;1. The output 'TestCircuitBoard&amp;1' shows that libroxml does not transform XML escape characters.  Will libroxml transform escape characters in the future? Thanks!

**Comment by blunderer** [comment]
This is indeed not yet supported, but there is no reason not to.
I'll try to work on adding this.

Note that my server got hacked recently, and my priority is to reinstall all, and secure it more. I'll make that the next priority. If you want to contribute some code, feel free to contact me directly or even send a patch.

Thanks

**Comment by greendow** [comment]
To blunderer:
I received your response. Thanks a lot!

**Comment by greendow** [comment]
If Libroxml can transform XML escape characters correctly in the future, please add a notice on the website:
http://www.libroxml.net/ . Thanks a lot!
