### ISSUE TITLE
roxml_add_node with ROXML_CDATA_NODE does not work

### ISSUE THREAD

**Issue by blocksebastian** [blunderer/libroxml#75]
I could not create CDATA entries.

Please find a patch attached:
[cdata_add_node_fix.txt](https://github.com/blunderer/libroxml/files/2869235/cdata_add_node_fix.txt)

**Comment by blunderer** [comment]
Thanks for the patch and sorry for the delay.
This is pushed to main, and will be included in next release.

**Comment by blocksebastian** [comment]
thank you for you fast reaction :+1:
