### ISSUE TITLE
roxml_add_node() should escape XML special characters

### ISSUE THREAD

**Issue by rmilecki** [blunderer/libroxml#76]
In order to produce a valid XML document some XML characters have to be escaped.
* Documentation: https://www.w3.org/TR/xml/#syntax
* Friendly description: https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

It's needed to avoid invalid XML syntax like
* `<foo>Lorem <p> ipsum</foo>`
* `<foo attr="Say "Hello"">`

**Comment by rmilecki** [comment]
Example code:
```
#include <roxml.h>
#include <stdio.h>

int main(void)
{
	node_t *root, *node;
	char *output = NULL;

	root = roxml_add_node(NULL, 0, ROXML_ELM_NODE, "tests", NULL);

	node = roxml_add_node(root, 0, ROXML_ELM_NODE, "item", NULL);
	roxml_add_node(node, 0, ROXML_ATTR_NODE, "attr", "Foo");

	node = roxml_add_node(root, 0, ROXML_ELM_NODE, "item", NULL);
	roxml_add_node(node, 0, ROXML_ATTR_NODE, "attr", "Quote chars: \" and '");

	node = roxml_add_node(root, 0, ROXML_ELM_NODE, "item", NULL);
	roxml_add_node(node, 0, ROXML_ATTR_NODE, "attr", "Special chars: &");

	node = roxml_add_node(root, 0, ROXML_ELM_NODE, "item", NULL);
	roxml_add_node(node, 0, ROXML_ATTR_NODE, "attr", "Condition: 3 < 5 is true");

	node = roxml_add_node(root, 0, ROXML_ELM_NODE, "item", NULL);
	roxml_add_node(node, 0, ROXML_ATTR_NODE, "attr", "Condition: 3 > 5 is false");

	roxml_add_node(root, 0, ROXML_ELM_NODE, "item", "HTML quote: <q>");

	roxml_add_node(root, 0, ROXML_ELM_NODE, "item", "Special chars: &");

	roxml_commit_buffer(root, &output, 1);
	if (output) {
		printf("%s\n", output);
	}

	roxml_close(root);

	return 0;
}
```
Output with 3.0.1:
```
<tests>
 <item attr="Foo"/>
 <item attr="Quote chars: " and '"/>
 <item attr="Special chars: &"/>
 <item attr="Condition: 3 < 5 is true"/>
 <item attr="Condition: 3 > 5 is false"/>
 <item>HTML quote: <q></item>
 <item>Special chars: &</item>
</tests>
```
Expected output:
```
<tests>
 <item attr="Foo"/>
 <item attr="Quote chars: &quot; and &apos;"/>
 <item attr="Special chars: &amp;"/>
 <item attr="Condition: 3 &lt; 5 is true"/>
 <item attr="Condition: 3 &gt; 5 is false"/>
 <item>HTML quote: &lt;q&gt;</item>
 <item>Special chars: &amp;</item>
</tests>
```

**Comment by rmilecki** [comment]
I checked `libroxml` sources and realized I may be capable of fixing that. Please take a look at attached PATCH.
[0001-roxml_edit-escape-XML-special-characters.txt](https://github.com/blunderer/libroxml/files/3107774/0001-roxml_edit-escape-XML-special-characters.txt)

**Comment by blunderer** [comment]
Hi,

thanks a lot for the patch. I took a quick look at it, but did not have much time today.
I'll take a closer look this weekend and, will try to add testing to it.

What do you prefer for my comments:
1) I submit your patch and apply some fixes on top
2) I send you my comments so you can change the code
3) I directly edit you patch and commit as is.

Let me know.

Thanks again

**Comment by rmilecki** [comment]
@blunderer: I'm OK with whatever works for you!

If you have time to work on that - it's great. If you are out of time and need me to do some fixups - just let me know.

**Comment by blunderer** [comment]
Hi,

I changed the way this is implemented as I did not want to introduce any incompatibility in case some people worked with escaping by themselves.
Also, I export the roxml_escape() function so that people can use it to unescape when reading using roxml_get_[name|content].

I also updated documentation and added a corresponding test case.
Feel free to let me know if the usage is not clear, I'll try to make it more explicit.

Thanks

**Comment by rmilecki** [comment]
Thanks @blunderer for looking at this!

I'd like to share 2 comments on your implementation:
1. As an end-user I'm not a big fan of that `ROXML_ESCAPE` macro. In my opinion it makes code a bit too complex, less clean and a bit harder to follow.
I **think** it should be possible to make `roxml_add_node()` call a `roxml_auto_escape()` and don't expose the later at all. So maybe we could have something cleaner, like
`roxml_add_node(NULL, 0, ROXML_ELM_NODE | ROXML_ESCAPED_MOD, "foo", "HTML quote: <q>");`
? What do you think about this?
I think that `ROXML_ESCAPED_MOD` looks better than a macro and is more future-proof. It allows adding more flags like that in a future. I don't think it would be possible to mix `ROXML_ESCAPE` macro with another similar one if we even need one.
2. I can understand the need for backward compatibility and it's something I didn't consider at first.
On the other hand it may be annoying to use `ROXML_ESCAPE` (or `ROXML_ESCAPED_MOD`) over and over in my project (I don't handle escaping on my own). I would really love to see some way of having escaping enabled by default.
   - Maybe a new function? Something like `roxml_add_node2()` or some better name?
   - Maybe some trick with a new define & in-header function/macro? Something like
`#define ROXML_ENABLE_AUTO_ESCAPE`
`#include <roxml.h>`

**Comment by blunderer** [comment]
That is a good point, I changed the roxml_add_node to only need the ROXML_ESCAPED_MOD.

Regarding adding a new version of the function, I would like to minimize the number of API function and make them as simple a possible.

Would manually defining in your project node types be an acceptable solution for you?

Something like:
#define MYPROJECT_ELM_NODE (ROXML_ELM_NODE | ROXML_ESCAPED_MOD) 
[...]

Thanks

**Comment by rmilecki** [comment]
Thank you @blunderer! I tested your implementation and (of course :) ) it works for me!

I guess I can live with something like `MYPROJECT_ELM_NODE` (or just `| ROXML_ESCAPED_MOD`).

I find escaping very important, I think everyone should use it by default (before they run into problems), so I thought it should be enabled by default. On the other hand it making it default **may** break things for some people. I guess there is no perfect solution to that.

Thanks again for your work on this!
