### ISSUE TITLE
How to include this library in a C program

### ISSUE THREAD

**Issue by xSomoy** [blunderer/libroxml#81]
I'm trying to include this library in my C program for Fuzz testing but am unable to do that. Can anyone explain to me how to do that?

**Comment by blunderer** [comment]
Hi,

integrating this in a C program should be exactly the same as using any other shared library:

1. Add the #include <roxml.h> to you r sources (or the double quoted version if the sources are not installed in the standard path)
2. Compile using -lroxml (and -L<path to the libroxml headers> if the sources are not installed in the standard path).

What did you try and what is failing for you?
